import { Category, Profile, Team, Player, Report, Match, Video, Club } from './types';

export const MOCK_CLUB: Club = {
  id: 'club-1',
  name: 'Club Scout DB',
  current_season: '2025/2026',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-senior', club_id: 'club-1', name: 'SENIOR', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'cat-juvenil', club_id: 'club-1', name: 'JUVENIL', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'cat-cadete', club_id: 'club-1', name: 'CADETE', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'cat-infantil', club_id: 'club-1', name: 'INFANTIL', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'cat-alevin', club_id: 'club-1', name: 'ALEVIN', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'cat-benjamin', club_id: 'club-1', name: 'BENJAMIN', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'cat-prebenjamin', club_id: 'club-1', name: 'PRE-BENJAMIN', season: '2025/2026', created_at: new Date().toISOString() },
];

export const MOCK_TEAMS: Team[] = [
  { id: 'team-1', name: 'Primer Equipo', club_name: 'Club Scout DB', category_id: 'cat-senior', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'team-2', name: 'Juvenil A', club_name: 'Club Scout DB', category_id: 'cat-juvenil', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'team-3', name: 'Cadete A', club_name: 'Club Scout DB', category_id: 'cat-cadete', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'team-4', name: 'Infantil A', club_name: 'Club Scout DB', category_id: 'cat-infantil', season: '2025/2026', created_at: new Date().toISOString() },
  { id: 'team-5', name: 'Alevin A', club_name: 'Club Scout DB', category_id: 'cat-alevin', season: '2025/2026', created_at: new Date().toISOString() },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'm-1',
    date: '2025-10-24T18:00:00Z',
    home_team: 'Pontevedra CF',
    away_team: 'RM Castilla',
    competition: 'Segunda B',
    venue: 'Estadio Municipal de Pasarón',
    score: '1-2',
    observed_players_ids: ['p-1', 'p-2'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'm-2',
    date: '2025-10-31T16:00:00Z',
    home_team: 'Barça Atlètic',
    away_team: 'Sevilla Atlético',
    competition: 'Segunda B',
    venue: 'Estadi Johan Cruyff',
    score: '2-0',
    observed_players_ids: ['p-3', 'p-4'],
    created_at: new Date().toISOString(),
  },
  ...Array.from({ length: 8 }).map((_, i) => ({
    id: `m-${i + 3}`,
    date: new Date(Date.now() - (i + i) * 86400000).toISOString(),
    home_team: `Equipo Local ${i + 3}`,
    away_team: `Equipo Visitante ${i + 3}`,
    competition: i % 2 === 0 ? 'Segunda B' : 'Juvenil A',
    venue: 'Campo Municipal',
    score: '0-0',
    observed_players_ids: [],
    created_at: new Date().toISOString(),
  }))
];

export const MOCK_PLAYERS: Player[] = [
  {
    id: 'p-1',
    club_id: 'club-1',
    first_name: 'Juan',
    last_name: 'Pérez',
    full_name: 'Juan Pérez',
    birth_year: 2005,
    calculated_age: 20,
    category_id: 'cat-2',
    current_team_id: 'team-1',
    club_name: 'Real Madrid Castilla',
    main_position: 'DC',
    dominant_foot: 'RIGHT',
    status: 'PRIORITY',
    interest_level: 5,
    global_rating: 4.5,
    potential_rating: 4.8,
    short_name: 'JUAN PÉREZ',
    lateralidad: 'DIESTRO',
    competition: 'DIVISIÓN DE HONOR',
    trajectory: [
      { season: '2025/26', team: 'Real Madrid Castilla', category: '1ª RFEF', minutes: 1240, matches_played: 18, starts: 14, substitutes: 4, goals: 8, assists: 3, yellow_cards: 2, red_cards: 0 },
      { season: '2024/25', team: 'Real Madrid Juv. A', category: 'Div. Honor', minutes: 2100, matches_played: 26, starts: 24, substitutes: 2, goals: 15, assists: 5, yellow_cards: 1, red_cards: 0 }
    ],
    rating_velo_despl: 4.5,
    rating_acel: 4.8,
    rating_fuerza: 3.5,
    rating_resis: 4.0,
    rating_agil: 4.2,
    rating_coord: 4.5,
    rating_velo_reac: 4.7,
    rating_poten: 4.0,
    rating_recup_fatiga: 3.8,
    rating_tenden_lesion: 1.5,
    rating_pase_corto: 4.2,
    rating_pase_largo: 3.5,
    rating_ctrl_balon: 4.5,
    rating_tiro: 4.8,
    rating_regate: 4.4,
    rating_conduc: 4.6,
    rating_superf_cont: 4.3,
    rating_despeje: 2.0,
    rating_entrada: 2.5,
    rating_pierna_menos: 3.2,
    rating_posic: 4.5,
    rating_cobertura: 3.0,
    rating_repliegue: 3.5,
    rating_ayuda_def: 3.2,
    rating_marcajes: 2.8,
    rating_dom_espacios: 4.3,
    rating_vigilancias: 3.5,
    rating_apoyos_off: 4.6,
    rating_desmarques: 4.9,
    rating_temporiz: 3.0,
    rating_liderazgo: 3.5,
    rating_caracter: 4.5,
    rating_competitiv: 4.8,
    rating_companerismo: 4.0,
    rating_mentalidad: 4.6,
    rating_agresividad: 3.8,
    rating_polivalencia: 3.2,
    rating_inteligencia: 4.4,
    rating_comunicacion: 3.5,
    rating_personalidad: 4.5,
    rating_juego_aereo: 3.2,
    strengths: ['Velocidad', 'Definición'],
    weaknesses: ['Juego aéreo'],
    has_video: true,
    has_images: true,
    possible_duplicate: false,
    created_by: 'u-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-2',
    club_id: 'club-1',
    first_name: 'Mateo',
    last_name: 'García',
    full_name: 'Mateo García',
    birth_year: 2004,
    calculated_age: 21,
    category_id: 'cat-1',
    current_team_id: 'team-1',
    club_name: 'RC Celta',
    main_position: 'MCO',
    dominant_foot: 'BOTH',
    status: 'TRACKING',
    interest_level: 4,
    global_rating: 4.2,
    potential_rating: 4.6,
    short_name: 'MATEO GARCÍA',
    lateralidad: 'ZURDO',
    competition: '1ª RFEF',
    trajectory: [
      { season: '2025/26', team: 'RC Celta Fortuna', category: '1ª RFEF', minutes: 1850, matches_played: 24, starts: 21, substitutes: 3, goals: 2, assists: 8, yellow_cards: 4, red_cards: 0 }
    ],
    rating_velo_despl: 4.0,
    rating_acel: 4.2,
    rating_fuerza: 3.2,
    rating_resis: 4.5,
    rating_agil: 4.0,
    rating_coord: 4.2,
    rating_velo_reac: 4.0,
    rating_poten: 3.5,
    rating_recup_fatiga: 4.2,
    rating_tenden_lesion: 1.0,
    rating_pase_corto: 4.8,
    rating_pase_largo: 4.9,
    rating_ctrl_balon: 4.6,
    rating_tiro: 3.8,
    rating_regate: 4.1,
    rating_conduc: 4.3,
    rating_superf_cont: 4.5,
    rating_despeje: 3.0,
    rating_entrada: 3.5,
    rating_pierna_menos: 2.5,
    rating_posic: 4.8,
    rating_cobertura: 4.0,
    rating_repliegue: 4.2,
    rating_ayuda_def: 4.1,
    rating_marcajes: 3.8,
    rating_dom_espacios: 4.7,
    rating_vigilancias: 4.5,
    rating_apoyos_off: 4.9,
    rating_desmarques: 4.8,
    rating_temporiz: 4.5,
    rating_liderazgo: 4.2,
    rating_caracter: 4.0,
    rating_competitiv: 4.5,
    rating_companerismo: 4.9,
    rating_mentalidad: 4.8,
    rating_agresividad: 3.5,
    rating_polivalencia: 4.6,
    rating_inteligencia: 4.9,
    rating_comunicacion: 4.8,
    rating_personalidad: 4.3,
    rating_juego_aereo: 2.8,
    has_video: true,
    has_images: false,
    possible_duplicate: false,
    created_by: 'u-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  ...Array.from({ length: 18 }).map((_, i) => {
    const categoriesList = ['cat-senior', 'cat-juvenil', 'cat-cadete', 'cat-infantil', 'cat-alevin', 'cat-benjamin', 'cat-prebenjamin'];
    const categoryId = categoriesList[i % categoriesList.length];
    const birthYearMap: Record<string, number> = {
      'cat-senior': 1998 + (i % 5),
      'cat-juvenil': 2007 + (i % 3),
      'cat-cadete': 2009 + (i % 2),
      'cat-infantil': 2011 + (i % 2),
      'cat-alevin': 2013 + (i % 2),
      'cat-benjamin': 2015 + (i % 2),
      'cat-prebenjamin': 2017 + (i % 2),
    };
    const birthYear = birthYearMap[categoryId] || 2005;
    
    return {
      id: `p-${i + 3}`,
      club_id: 'club-1',
      first_name: `Jugador ${i + 3}`,
      last_name: `Ejemplo ${i + 3}`,
      full_name: `Jugador Demo ${i + 3}`,
      birth_year: birthYear,
      calculated_age: new Date().getFullYear() - birthYear,
      category_id: categoryId,
      current_team_id: `team-${(i % 5) + 1}`,
      club_name: i % 2 === 0 ? 'RC Celta' : 'Pantevedra CF',
      main_position: ['POR', 'DFC', 'MC', 'ED', 'EI', 'DC'][i % 6],
      dominant_foot: ['LEFT', 'RIGHT', 'BOTH'][i % 3] as any,
      status: ['NEW', 'TRACKING', 'PRIORITY', 'INTERESTING'][i % 4] as any,
      interest_level: (i % 5) + 1,
      global_rating: 3.0 + (Math.random() * 2),
      potential_rating: 4.0 + (Math.random() * 1),
      has_video: i % 2 === 0,
      has_images: i % 3 === 0,
      possible_duplicate: false,
      created_by: 'u-1',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      // Add random ratings for new fields
      rating_velo_despl: 1 + Math.random() * 4,
      rating_acel: 1 + Math.random() * 4,
      rating_fuerza: 1 + Math.random() * 4,
      rating_resis: 1 + Math.random() * 4,
      rating_agil: 1 + Math.random() * 4,
      rating_coord: 1 + Math.random() * 4,
      rating_velo_reac: 1 + Math.random() * 4,
      rating_poten: 1 + Math.random() * 4,
      rating_recup_fatiga: 1 + Math.random() * 4,
      rating_tenden_lesion: 1 + Math.random() * 2,
      rating_pase_corto: 1 + Math.random() * 4,
      rating_pase_largo: 1 + Math.random() * 4,
      rating_ctrl_balon: 1 + Math.random() * 4,
      rating_tiro: 1 + Math.random() * 4,
      rating_regate: 1 + Math.random() * 4,
      rating_conduc: 1 + Math.random() * 4,
      rating_superf_cont: 1 + Math.random() * 4,
      rating_despeje: 1 + Math.random() * 4,
      rating_entrada: 1 + Math.random() * 4,
      rating_pierna_menos: 1 + Math.random() * 4,
      rating_posic: 1 + Math.random() * 4,
      rating_cobertura: 1 + Math.random() * 4,
      rating_repliegue: 1 + Math.random() * 4,
      rating_ayuda_def: 1 + Math.random() * 4,
      rating_marcajes: 1 + Math.random() * 4,
      rating_dom_espacios: 1 + Math.random() * 4,
      rating_vigilancias: 1 + Math.random() * 4,
      rating_apoyos_off: 1 + Math.random() * 4,
      rating_desmarques: 1 + Math.random() * 4,
      rating_temporiz: 1 + Math.random() * 4,
      rating_liderazgo: 1 + Math.random() * 4,
      rating_caracter: 1 + Math.random() * 4,
      rating_competitiv: 1 + Math.random() * 4,
      rating_companerismo: 1 + Math.random() * 4,
      rating_mentalidad: 1 + Math.random() * 4,
      rating_agresividad: 1 + Math.random() * 4,
      rating_polivalencia: 1 + Math.random() * 4,
      rating_inteligencia: 1 + Math.random() * 4,
      rating_comunicacion: 1 + Math.random() * 4,
      rating_personalidad: 1 + Math.random() * 4,
      rating_juego_aereo: 1 + Math.random() * 4,
    };
  })
];

export const MOCK_REPORTS: Report[] = [
  ...Array.from({ length: 10 }).map((_, i) => ({
    id: `r-${i + 1}`,
    player_id: `p-${(i % 10) + 1}`,
    match_id: `m-${(i % 2) + 1}`,
    observer_id: 'u-1',
    report_date: new Date(Date.now() - i * 86400000).toISOString(),
    recommendation: (i % 3 === 0 ? 'PRIORITY' : 'TRACKING'),
    match_rating: 3 + (i % 3),
    created_at: new Date().toISOString(),
    technical_comment: 'Excelente control orientado y visión de juego.',
    tactical_comment: 'Gran lectura de espacios y ocupación racional del terreno.',
    strengths: ['Velocidad', 'Visión'],
    weaknesses: ['Fuerza física'],
  }))
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'v-1',
    player_id: 'p-1',
    match_id: 'm-1',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    platform: 'YouTube',
    title: 'Goles vs Pontevedra',
    is_key: true,
    pending_review: false,
    created_at: new Date().toISOString(),
  }
];

export const MOCK_USERS: Profile[] = [
  {
    id: 'u-1',
    user_id: 'au-1',
    full_name: 'Scout Principal',
    email: 'scout@club.com',
    role: 'SUPERADMIN',
    club_id: 'club-1',
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
